const constants = {
    FETCH_PERSONS: "FETCH_PERSONS",
    FETCH_PERSONS_SUCCESS: "FETCH_PERSONS_SUCCESS",
    FETCH_PERSON: "FETCH_PERSON",
    FETCH_PERSON_SUCCESS: "FETCH_PERSON_SUCCESS",
    ADD_PERSON: "ADD_PERSON",
    ADD_PERSON_SUCCESS: "ADD_PERSON_SUCCESS",
    DELETE_PERSON: "DELETE_PERSON",
    DELETE_PERSON_SUCCESS: "DELETE_PERSON_SUCCESS",
    OPEN_PERSON_VIEW: "OPEN_PERSON_VIEW",
    CLOSE_PERSON_VIEW: "CLOSE_PERSON_VIEW",
    OPEN_CREATE_PERSON_FORM: "OPEN_CREATE_PERSON_FORM",
    CLOSE_CREATE_PERSON_FORM: "CLOSE_CREATE_PERSON_FORM",
    SEARCH_PERSON: "SEARCH_PERSON",
    ERROR: "ERROR",
};
export default constants;