const constants = {
    FETCH_PERSONS: "FETCH_PERSONS",
    FETCH_PERSONS_SUCCESS: "FETCH_PERSONS_SUCCESS",
    FETCH_PERSON: "FETCH_PERSON",
    FETCH_PERSON_SUCCESS: "FETCH_PERSON_SUCCESS",
    ERROR: "ERROR",
};
export default constants;