const constants = {
    FETCH_PERSONS: "FETCH_PERSONS",
    FETCH_PERSONS_SUCCESS: "FETCH_PERSONS_SUCCESS",
    FETCH_PERSON: "FETCH_PERSON",
    FETCH_PERSON_SUCCESS: "FETCH_PERSON_SUCCESS",
    DELETE_PERSON: "DELETE_PERSON",
    DELETE_PERSON_SUCCESS: "DELETE_PERSON_SUCCESS",
    OPEN_PERSON_VIEW: "OPEN_PERSON_VIEW",
    CLOSE_PERSON_VIEW: "CLOSE_PERSON_VIEW",
    ERROR: "ERROR",
};
export default constants;